name: faas
namespace: agcoolserve3
runtime: go
image: quay.io/agroom/coolstorefaas:latest
imageDigest: ""
trigger: events
builder: quay.io/boson/faas-go-builder
builderMap:
  default: quay.io/boson/faas-go-builder
env:
  ITEM: web-
  SEARCH: 'Created pod:'
annotations: {}
