kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  namespace: my-project1
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: event
          ports:
            - name: http-server
              containerPort: 8080
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-event-service
  labels:
    app: loyalty-event-service
spec:
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    app: loyalty-event-service
---
apiVersion: v1
kind: Route
metadata:
  name: web
spec:
  to:
    kind: Service
    name: web
