---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: jar-pipeline
spec:
  resources:
  - name: component-git
    type: git
  params:
  - name: componentName
    default: sample
    description: The name of the component
  tasks:
  - name: build-jar
    taskRef:
      name: maven-build
    resources:
      inputs:
      - name: source-repo
        resource: component-git
      outputs:
      - name: source-repo
        resource: component-git
  - name: build-image
    taskRef:
      name: s2i-jar
    runAfter:
      - build-jar
    resources:
      inputs:
      - name: source-repo
        resource: component-git
        from: 
        - build-jar
    params:
    - name: componentName
      value: '$(params.componentName)'
  - name: get-next-tag
    taskRef:
      name: increment-version
    runAfter:
      - build-jar
    resources:
      inputs:
      - name: source-repo
        resource: component-git
        from: 
        - build-jar
      outputs:
      - name: source-repo
        resource: component-git
    params:
    - name: componentName
      value: '$(params.componentName)'
  - name: tag-image
    taskRef:
      name: oc-tag-image
    runAfter:
      - get-next-tag
      - build-image
    resources:
      inputs:
      - name: source-repo
        resource: component-git
        from: 
        - get-next-tag
    params:
    - name: componentName
      value: '$(params.componentName)'
  - name: deploy
    taskRef:
      name: oc-deploy
    runAfter:
      - tag-image
    params:
    - name: componentName
      value: '$(params.componentName)'