
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: oc-tag-image
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
    params:
      - name: componentName
        default: sample
        description: The name of the component
  steps:
    - name: tag
      image: 'quay.io/openshift/origin-cli:latest'
      command:
        - /usr/bin/bash
      args:
        - '-c'
        - >-
          oc tag $(inputs.params.componentName):latest $(inputs.params.componentName):$(cat /workspace/source-repo/next_version.txt)
    - name: update-deployment-config
      image: 'quay.io/openshift/origin-cli:latest'
      command:
        - /usr/bin/bash
      args:
        - '-c'
        - >-
          PROJECT_NAME=$(oc get is $(inputs.params.componentName) -o=jsonpath='{.metadata.namespace}') && 
          oc patch dc $(inputs.params.componentName) --patch '{"spec": {"template": {"spec": {"containers": [{"name": "$(inputs.params.componentName)", "image": "image-registry.openshift-image-registry.svc:5000/'${PROJECT_NAME}'/$(inputs.params.componentName):'$(cat /workspace/source-repo/next_version.txt)'"}]}}}}'