apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: event-display
 namespace: my-project1
spec:
 template:
   spec:
     containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
 name: testevents-trigger1
 namespace: my-project1
spec:
 subscriber:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: event-display
