apiVersion: v1
kind: Service
metadata:
 name: event-display2
 namespace: my-project1
spec:
 ports:
   - name: 8080-tcp
     protocol: TCP
     port: 80
     targetPort: 8080
 template:
   spec:
     containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
 name: testevents-trigger1
 namespace: my-project1
spec:
 subscriber:
   ref:
     apiVersion: v1
     kind: Service
     name: event-display2
