apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
 name: testevents-trigger2
 namespace: my-project1
spec:
 filter:
   attributes:
     type: web-wakeup
 subscriber:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: inventory
 
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
 name: testevents-trigger3
 namespace: my-project1
spec:
 filter:
   attributes:
     type: web-wakeup
 subscriber:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: catalog
