apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: bind-webserver
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: web
