kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java:11
  SourceLocation: target/catalog-1.0-SNAPSHOT.jar
  SourceType: binary
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: coolstore
  Project: my-project1
  Name: catalog
  Url:
  - Name: catalog
    Port: 8080
